<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata Sandi_sc-1auyczi-2 eWsBfk sc-1uj_b30e5a</name>
   <tag></tag>
   <elementGuidId>984ec678-0212-4e3f-959d-de2b5e631aeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='P@ssw0rd009']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55678d44-5391-48a1-a22b-6217fe2a40c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>33e80867-6095-4dfe-a072-dcbcb1615670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7afc965f-a0d5-47c4-bf01-1813c4e03515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1auyczi-2 eWsBfk sc-1uj1rn4-2 gFJWwS</value>
      <webElementGuid>48c99ee5-80ea-4ffb-a0b1-f8b242e6f49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>e2bc0713-dc54-4769-a5ba-80f5f5906816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P@ssw0rd009</value>
      <webElementGuid>0c22cafc-5ddf-4f01-8bcb-c9274bde36c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-vswk66-0 fJiAhm&quot;]/div[@class=&quot;sc-rkmhgf-0 hWVtzq&quot;]/div[@class=&quot;sc-1crxk01-0 gVKylD&quot;]/div[@class=&quot;sc-1crxk01-0 kllYhf&quot;]/div[@class=&quot;sc-1crxk01-0 inhaeL&quot;]/div[@class=&quot;sc-1uj1rn4-3 iuAPRv&quot;]/input[@class=&quot;sc-1auyczi-2 eWsBfk sc-1uj1rn4-2 gFJWwS&quot;]</value>
      <webElementGuid>2923d85e-3c1f-48de-a9c9-9ca6bc55fd19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='P@ssw0rd009']</value>
      <webElementGuid>0b0ce84a-514c-449e-9be1-b1dd4f17e6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>ccd71689-e196-4ed1-b994-cdbbf323a198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>2cd190ec-3c0c-4417-a2e3-86740fca43f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password']</value>
      <webElementGuid>31d50f95-00c9-431b-9747-bb7488f9bfed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
