<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Email atau Nomor HP_sc-1auyczi_6f84f0</name>
   <tag></tag>
   <elementGuidId>1afdbebc-33eb-4225-b0db-cb3e0f128a4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.sc-1auyczi-2.bIZmZe.sc-1uj1rn4-2.gFJWwS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8ed9546-1448-4b86-a3ae-597b652a1d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>d6dba1bf-c592-4593-bd75-56eaf03b51a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c4f5826-feed-40c1-9b1d-ff1189d3fbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1auyczi-2 bIZmZe sc-1uj1rn4-2 gFJWwS</value>
      <webElementGuid>b17ec700-5cad-437a-8f31-64d87f58047f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>f748d5da-3ec4-4102-9b13-26702b8c656a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-vswk66-0 fJiAhm&quot;]/div[@class=&quot;sc-rkmhgf-0 hWVtzq&quot;]/div[@class=&quot;sc-1crxk01-0 gVKylD&quot;]/div[@class=&quot;sc-1crxk01-0 kllYhf&quot;]/div[@class=&quot;sc-1crxk01-0 inhaeL&quot;]/div[@class=&quot;sc-1uj1rn4-3 iuAPRv&quot;]/input[@class=&quot;sc-1auyczi-2 bIZmZe sc-1uj1rn4-2 gFJWwS&quot;]</value>
      <webElementGuid>4393755f-ca7e-4369-9346-f201c5ec71b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>07adf845-8df6-42a9-8ad3-503a93d5a893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>4876e870-0141-408f-93f4-c900dae563a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f20f7cf7-cb4e-40f8-b11f-03e8ed4ae1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>277a7e2a-272a-4fc6-83df-313a6f42191b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
